export const SEARCH_COUNTRIES_BY_NAME = "SEARCH_COUNTRIES_BY_NAME";
export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRIES_BY_ID = "FETCH_COUNTRIES_BY_ID";
export const CLEAR_SEARCH = "CLEAR_SEARCH;";
